on: [push, pull_request]
name: Test
jobs:
  lint:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - uses: actions/checkout@v3

      - uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          skip-pkg-cache: true
          skip-build-cache: true
  test:
    strategy:
      matrix:
        go-version: [ 1.19.x]
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -race -coverprofile cover.out -vet=off ./...
      - name: FuzzTest
        run: go test -fuzz=FuzzSetString -fuzztime=15s ./...
